{% set name = "google-auth" %}
{% set version = "1.27.0" %}
{% set sha256 = "da5218cbf33b8461d7661d6b4ad91c12c0107e2767904d5e3ae6408031d5463e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python >=3.6
    - cachetools >=2.0.0,<5.0
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<5
    - setuptools >=40.3.0
    - six >=1.9.0
    - aiohttp >=3.6.2,<4.0.0dev

test:
  requires:
    - python
    - pip
  imports:
    - google.auth
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: This library provides the ability to authenticate to Google APIs using various methods. It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io/en/latest/
  dev_url: https://github.com/googleapis/google-auth-library-python

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
