{% set name = "google-auth" %}
{% set version = "2.25.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-auth-{{ version }}.tar.gz
  sha256: 42f707937feb4f5e5a39e6c4f343a17300a459aaf03141457ba505812841cc40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - cachetools >=2.0.0,<6.0
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<5
    # aiohttp and requests extras
    - aiohttp >=3.6.2,<4.0.0
    - requests >=2.20.0,<3.0.0
    # pyopenssl extra
    - pyopenssl >=20.0.0
    - cryptography >=38.0.3
    # reauth extra
    - pyu2f >=0.1.5

test:
  requires:
    - python
    - pip
  imports:
    - google.auth
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: This library provides the ability to authenticate to Google APIs using various methods. It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io/en/latest/
  dev_url: https://github.com/googleapis/google-auth-library-python

extra:
  recipe-maintainers:
    - xylar
    - jan-janssen
    - jreback
    - parthea
    - theacodes
    - tswast
