{% set name = "google-auth" %}
{% set version = "2.5.0" %}
{% set sha256 = "6577bbf990ef342a24e12e0c8e9d364af6642acdf206c9045bdb8e039fb4fec9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python >=3.6
    - cachetools >=2.0.0,<5.0
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<5
    - setuptools >=40.3.0
    - six >=1.9.0
    - aiohttp >=3.6.2,<4.0.0dev
    - requests >=2.20.0,<3.0.0dev
    - pyopenssl >=20.0.0
    - pyu2f >=0.1.5

test:
  requires:
    - python
    - pip
  imports:
    - google.auth
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: This library provides the ability to authenticate to Google APIs using various methods. It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io/en/latest/
  dev_url: https://github.com/googleapis/google-auth-library-python

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
